name: nahoocare
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.1
  get_it: ^7.2.0
  google_fonts: ^6.1.0
  equatable: ^2.0.5
  dartz: ^0.10.1
  intl: ^0.18.1
  http: ^1.1.0
  flutter_dotenv: ^5.1.0
  permission_handler: ^12.0.0+1
  shared_preferences: ^2.5.3
  connectivity_plus: ^6.1.4
  dio: ^5.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
 


flutter:
  uses-material-design: true
  assets: 
    - .env